### ISSUE TITLE
i cannot find ConfigAdapter class 

### ISSUE THREAD

**Issue by hossamelsharkawy** [pradeepksingh/Android-USB-printer#2]
https://github.com/pradeepksingh/Android-USB-printer/blob/master/com/pradeep/usbprinter/MainActivity.java#L14
-   private ConfigAdapter datasource;

**Comment by pradeepksingh** [comment]
Not required. Remove it from main activity.

On Wed, Aug 31, 2016 at 4:26 PM, hossamhassanegypt <notifications@github.com
